melfore/konva-timeline

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

Configure git-cz and commitlint

---

.github/workflows/release.yml
.nycrc
.storybook/main.ts
package-lock.json
package.json
src/@components/Task/index.stories.tsx
src/@utils/stories.tsx

This PR closes #28 adding test suite for storybook test-runner in release CI

Add test suite

---

.github/workflows/release.yml

Fix for concurrently set of commands to be run

---

.github/workflows/release.yml

Force tcp address for wait-on command

---

src/@components/Task/index.tsx
src/@contexts/Timeline.tsx
src/@utils/timeline.ts
src/KonvaTimeline/index.stories.tsx

Implement snap to grid when dragging

---

package.json
tsconfig.json

Build in dist folder

---

README.md
package-lock.json
package.json
src/@stories/index.mdx

This PR closes #64 and closes #60

Fix failed to compile

---

README.md
src/@stories/index.mdx

Updated install notes for node < 7

---

src/@components/Task/index.tsx

This PR closes #69 and refines #72 adding logDebug calls

Fix initial rounding

---

src/@components/ResourceHeader/index.tsx
src/@components/Task/index.tsx
src/@components/TaskTooltip/index.tsx
src/@components/TasksLayer/index.tsx
src/@components/Timeline/index.tsx
src/@contexts/Timeline.tsx
src/@stories/index.mdx
src/@utils/resources.ts
src/@utils/timeline.ts
src/KonvaTimeline/index.stories.tsx
src/grid/Cell/index.tsx
src/grid/Row/index.tsx
tsconfig.json

This PR closes #57 and closes #59

Minor Grid and Task features

---

CHANGELOG.md
src/@components/Task/index.tsx

[Task] Fixed drag snap when ratio too small 

---

src/index.ts

Added exports for common types and utilities

---

src/index.ts
src/tasks/utils/tasks.test.ts
src/tasks/utils/tasks.ts
src/timeline/TimelineContext.tsx
src/utils/operations.ts

[Tasks] Refactored filter function with errors

---

src/tasks/components/Layer/index.tsx
src/timeline/index.tsx

[Task] Tooltip auto closes when scrolling

---

CHANGELOG.md
src/KonvaTimeline/stories-data.ts
src/tasks/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/utils/theme.test.ts
src/utils/theme.ts

[Task] Wrong foreground color for black white

---

.vscode/konva-timeline-scripts.code-snippets
src/tasks/components/Layer/index.stories.tsx
src/tasks/components/Task/index.tsx

[Task] Fixed default hex color string

---

CHANGELOG.md
src/tasks/utils/tasks.test.ts
src/tasks/utils/tasks.ts
src/timeline/TimelineContext.tsx
src/utils/utils.ts

This PR closes #108, closes #95

[Timeline] Tasks validation and onErrors cb

---

CHANGELOG.md
src/tasks/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/TaskResizeHandler/index.tsx
src/tasks/utils/tasks.test.ts
src/tasks/utils/tasks.ts

[Task] Implement resize

---

src/grid/Cell/index.tsx
src/grid/CellGroup/index.tsx
src/grid/Cells/index.tsx
src/grid/Layer/index.tsx
src/timeline/TimelineContext.tsx
src/utils/time-resolution.ts
src/utils/time.ts

[Timeline] Added display of unit above

---

src/timeline/TimelineContext.tsx
src/utils/time.test.ts
src/utils/time.ts

[KonvaTimeLine] refactored validTime function

---

src/utils/utils.ts

[KonvaTimeLine] PerformanceCheck function refactor

---

src/timeline/TimelineContext.tsx
src/utils/time.ts

[KonvaTimeLine]Added Range validation

---

CHANGELOG.md
src/timeline/TimelineContext.tsx
src/utils/timeline.ts

70 drag do not inherit resolution

---

CHANGELOG.md
src/grid/CellGroup/index.tsx
src/grid/Cells/index.tsx
src/timeline/TimelineContext.tsx
src/utils/timeBlockArray.ts

[TimeLine] Added AboveTimeBlocksVisible

---

CHANGELOG.md
src/KonvaTimeline/index.stories.tsx
src/KonvaTimeline/yearly-scenario.stories.tsx
src/resources/utils/resources.ts
src/tasks/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/utils/tasks.ts
src/utils/konva.ts
src/utils/theme.ts

[Task] Add completed percentage prop

---

CHANGELOG.md
src/grid/Cell/index.tsx
src/grid/CellGroup/index.tsx
src/grid/Row/index.tsx
src/resources/components/Header/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/Tooltip/index.tsx
src/tasks/utils/tasks.ts
src/utils/theme.ts

[ToolTip] tooltip position

---

CHANGELOG.md
src/tasks/components/Tooltip/index.tsx

[Tooltip] Add tooltip content

---

CHANGELOG.md
src/KonvaTimeline/yearly-scenario.stories.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/Tooltip/index.tsx

[Tooltip] Onmove tooltip position

---

src/tasks/components/Tooltip/index.tsx

 [ToolTip] Added style

---

CHANGELOG.md
src/tasks/components/Tooltip/index.tsx

[ToolTip] Refactoring

---

CHANGELOG.md
README.md
package.json
src/@stories/index.mdx
src/tasks/components/Task/index.tsx
src/tasks/utils/tasks.ts

This PR closes #159 and closes #103

[Task] Drag and drop between resources is sometimes laggy

---

CHANGELOG.md
src/tasks/components/Tooltip/index.tsx

[ToolTip] Position error

---

CHANGELOG.md
src/tasks/components/Task/index.tsx

[Task] Dragged should not go outside time

---

CHANGELOG.md
src/KonvaTimeline/index.stories.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/Tooltip/index.tsx
src/timeline/TimelineContext.tsx

[ToolTip] Added localization props

---

CHANGELOG.md
src/KonvaTimeline/index.stories.tsx
src/grid/CellGroup/index.tsx
src/timeline/TimelineContext.tsx
src/utils/time-resolution.ts
src/utils/timeBlockArray.ts

[TimeLine] Added dateLocale prop

---

src/grid/Cell/index.tsx
src/grid/CellGroup/index.tsx
src/utils/time-resolution.ts

[Grid] Improve display of time

---

src/KonvaTimeline/index.stories.tsx
src/KonvaTimeline/monthly-scenario.stories.tsx
src/KonvaTimeline/yearly-scenario.stories.tsx
src/tasks/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/utils/tasks.ts
src/timeline/TimelineContext.tsx
src/timeline/index.tsx

[TimeLine] Add task through selected area

---

.github/workflows/release.yml

[CI] Replaced deprecated command set-output

---

CHANGELOG.md
package.json

[Chore] Review browserlist options

---

src/tasks/components/Task/index.tsx

[Task] Created pattern for incomplete taskColor

---

CHANGELOG.md
src/tasks/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/timeline/index.tsx

[TimeLine] Fixed AreaSelect

---

CHANGELOG.md
src/timeline/index.tsx

[TimeLine] Fixed AreaSelect error

---

src/tasks/components/Task/index.tsx
src/timeline/TimelineContext.tsx
src/utils/theme.ts

[Task] new incomplete color, added pattern prop

---

CHANGELOG.md
src/tasks/components/Task/index.tsx
src/timeline/index.tsx

[TimeLine] AreaSelect allowed negative selection

---

src/tasks/utils/tasks.ts

[Task] Time return

---

.nycrc

Test coverage

---

src/KonvaTimeline/line-scenario.stories.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/TaskLine/index.tsx
src/timeline/TimelineContext.tsx
src/timeline/index.tsx

[TimeLine] Reported start-end range

---

CHANGELOG.md
src/KonvaTimeline/line-scenario.stories.tsx
src/grid/Cell/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/components/TaskLine/index.tsx
src/tasks/utils/tasks.ts
src/utils/timeBlockArray.ts

[Task] Fixed time return

---

.github/workflows/release.yml

Updated node version

---

src/timeline/index.tsx

[Task]Fixed areaselect return

---

src/KonvaTimeline/index.stories.tsx
src/resources/components/Header/index.tsx
src/resources/components/Layer/index.tsx
src/tasks/components/Task/index.tsx
src/tasks/utils/tasks.ts
src/timeline/TimelineContext.tsx

✅ Closes: #219 and Closes: #220
Feature:
1. Custom task color
2. Event handler for resource click

[Task] Added custom color for single task
